{"name": "test_case013", "status": "broken", "statusDetails": {"message": "KeyError: 'id'", "trace": "file = 'data_infor', data = ('id',), bath = '/Users/jiahan/Desktop/TXT_interface/logic/files/{}.json'\nf_w = <_io.TextIOWrapper name='/Users/jiahan/Desktop/TXT_interface/logic/files/data_infor.json' mode='r+' encoding='utf-8'>, data_json = {}\n\n    def extract_data (file,*data):\n        bath = app.base_dir + '/files/{}.json'\n        with open(bath.format(file), 'r+', encoding='utf-8') as f_w:\n            data_json={}\n            res_json=json.loads(f_w.read())\n            try:\n    \n                for i in data:\n>                   if res_json.get(i) ==None:\nE                   AttributeError: 'list' object has no attribute 'get'\n\n../file_operate.py:91: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test1.TestClass object at 0x7fda37cf16c0>\n\n    def test_case013(self):\n>       res013 = dataset_testing_files()\n\ntest1.py:65: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest05_datasets.py:182: in dataset_testing_files\n    res_dataset_training_files = data.datasetfiles({'dataset': file_operate.extract_data(data_infor, 'id').get('id'), 'predict_files': str(file_id_list)})\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfile = 'data_infor', data = ('id',), bath = '/Users/jiahan/Desktop/TXT_interface/logic/files/{}.json'\nf_w = <_io.TextIOWrapper name='/Users/jiahan/Desktop/TXT_interface/logic/files/data_infor.json' mode='r+' encoding='utf-8'>, data_json = {}\n\n    def extract_data (file,*data):\n        bath = app.base_dir + '/files/{}.json'\n        with open(bath.format(file), 'r+', encoding='utf-8') as f_w:\n            data_json={}\n            res_json=json.loads(f_w.read())\n            try:\n    \n                for i in data:\n                    if res_json.get(i) ==None:\n                        print(\"未获取到值：\",i)\n    \n                    data_json[i]=res_json.get(i)\n                    #\n            except:\n                for i_res in res_json:\n                    for i_data in data:\n>                       if i_res[i_data]==None:\nE                       KeyError: 'id'\n\n../file_operate.py:99: KeyError"}, "attachments": [{"name": "stdout", "source": "5482e93b-6f53-45e7-b1a8-73cf8699baf4-attachment.txt", "type": "text/plain"}], "start": 1669172378048, "stop": 1669172378050, "uuid": "41256d82-191c-4292-bcdd-18a7f3b7e2e8", "historyId": "7f43969119276fee89895456fa9b3f9f", "testCaseId": "8ef05d5ed9d813151144ef85c15d1b7b", "fullName": "test1.TestClass#test_case013", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init')"}, {"name": "suite", "value": "test1"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "jiahandeMacBook-Pro.local"}, {"name": "thread", "value": "5006-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test1"}]}