{"name": "test_case011", "status": "broken", "statusDetails": {"message": "KeyError: 'id'", "trace": "file = 'data_infor', data = ('id',), bath = '/Users/jiahan/Desktop/TXT_interface/logic/files/{}.json'\nf_w = <_io.TextIOWrapper name='/Users/jiahan/Desktop/TXT_interface/logic/files/data_infor.json' mode='r+' encoding='utf-8'>, data_json = {}\n\n    def extract_data (file,*data):\n        bath = app.base_dir + '/files/{}.json'\n        with open(bath.format(file), 'r+', encoding='utf-8') as f_w:\n            data_json={}\n            res_json=json.loads(f_w.read())\n            try:\n    \n                for i in data:\n>                   if res_json.get(i) ==None:\nE                   AttributeError: 'list' object has no attribute 'get'\n\n../file_operate.py:91: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test1.TestClass object at 0x7fda37cf13c0>\n\n    def test_case011(self):\n>       res011 = dataset_all_files()\n\ntest1.py:57: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntest05_datasets.py:133: in dataset_all_files\n    res_dataset_all_files =data.dataset_files({'dataset':file_operate.extract_data('data_infor' ,'id').get('id')})\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfile = 'data_infor', data = ('id',), bath = '/Users/jiahan/Desktop/TXT_interface/logic/files/{}.json'\nf_w = <_io.TextIOWrapper name='/Users/jiahan/Desktop/TXT_interface/logic/files/data_infor.json' mode='r+' encoding='utf-8'>, data_json = {}\n\n    def extract_data (file,*data):\n        bath = app.base_dir + '/files/{}.json'\n        with open(bath.format(file), 'r+', encoding='utf-8') as f_w:\n            data_json={}\n            res_json=json.loads(f_w.read())\n            try:\n    \n                for i in data:\n                    if res_json.get(i) ==None:\n                        print(\"未获取到值：\",i)\n    \n                    data_json[i]=res_json.get(i)\n                    #\n            except:\n                for i_res in res_json:\n                    for i_data in data:\n>                       if i_res[i_data]==None:\nE                       KeyError: 'id'\n\n../file_operate.py:99: KeyError"}, "start": 1669172378019, "stop": 1669172378019, "uuid": "ad369e2f-b42c-4e21-b493-d733be65c4ab", "historyId": "f3864cc454577aa42f44bd73c8d39211", "testCaseId": "f9657e8a14dc28062fab4c7dbec134aa", "fullName": "test1.TestClass#test_case011", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init')"}, {"name": "suite", "value": "test1"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "jiahandeMacBook-Pro.local"}, {"name": "thread", "value": "5006-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test1"}]}